# reverse order

#' @include spec-compliance.R
#' @include spec-compliance-read-only.R
#' @include spec-compliance-methods.R
#' @include spec-meta.R
#' @include spec-meta-bind-named-dollar.R
#' @include spec-meta-bind-named-colon.R
#' @include spec-meta-bind-positional-dollar.R
#' @include spec-meta-bind-positional-qm.R
#' @include spec-meta-get-info-result.R
#' @include spec-meta-get-rows-affected.R
#' @include spec-meta-get-row-count.R
#' @include spec-meta-column-info.R
#' @include spec-meta-get-statement.R
#' @include spec-meta-is-valid-result.R
#' @include spec-meta-is-valid-connection.R
#' @include spec-sql.R
#' @include spec-sql-list-fields.R
#' @include spec-sql-list-tables.R
#' @include spec-sql-read-write-roundtrip.R
#' @include spec-sql-read-write-table.R
#' @include spec-sql-quote-identifier.R
#' @include spec-sql-quote-string.R
#' @include spec-result.R
#' @include spec-result-roundtrip.R
#' @include spec-result-create-table-with-data-type.R
#' @include spec-result-get-query.R
#' @include spec-result-fetch.R
#' @include spec-result-send-query.R
#' @include spec-connection.R
#' @include spec-connection-stress.R
#' @include spec-connection-get-info.R
#' @include spec-connection-data-type.R
#' @include spec-connection-connect.R
#' @include spec-driver.R
#' @include spec-driver-stress.R
#' @include spec-driver-get-info.R
#' @include spec-driver-data-type.R
#' @include spec-driver-constructor.R
#' @include spec-driver-class.R
#' @include spec-getting-started.R
#' @include spec.R
NULL
